---
# tasks file for roles/install_docker
- name: "Desinstaller les composants docker si deja presents"
  ansible.builtin.apt:
    name:
      - docker.io,docker-doc,docker-compose,podman-docker,containerd,runc
    state: absent

- name: "Installer ca-certificates et curl"